export default {
  alarmClock: [
    "time",
    "clock",
    "watch",
    "timetable",
    "opening hours",
    "schedule",
    "alarm",
    "morning"
  ],
  bottle: [
    "food",
    "ecology",
    "waste",
    "drink",
    "water",
    "bottle",
    "plastic",
    "milk"
  ],
  bowl: ["food", "bowl", "soup", "meal", "lunch", "dinner"],
  burger: ["food", "fast food", "to go", "lunch", "dinner", "meal"],
  calendar: [
    "calendar",
    "date",
    "meeting",
    "year",
    "time",
    "schedule",
    "timetable"
  ],
  camera: ["camera", "photo", "photography", "art", "image", "portrait"],
  clock: ["time", "clock", "watch", "timetable", "opening hours", "schedule"],
  cloud: ["nature", "cloud", "weather", "rain", "ecology", "eco", "weather"],
  coffeeToGo: ["coffee", "drink", "tea", "to go", "food"],
  computerBasic: ["computer", "technology", "ai", "work"],
  computerHeart: ["computer", "technology", "heart", "love"],
  drinkStraw: ["drink", "straw", "summer", "chill", "food"],
  drinkToGo: ["drink", "to go", "straw", "summer", "chill", "food"],
  fileTxt: ["file", "computer", "txt", "document", "paper", "notes"],
  file: ["file", "computer", "txt", "document", "notes", "paper"],
  foodCart: [
    "food",
    "cart",
    "to go",
    "fast food",
    "food stand",
    "ice cream",
    "market"
  ],
  frenchFries: ["french fries", "food", "fast food"],
  iceCream: [
    "food",
    "icecream",
    "ice cream",
    "sweet",
    "summer",
    "holidays",
    "vacation",
    "relax"
  ],
  iceCreamBite: [
    "food",
    "icecream",
    "ice cream",
    "sweet",
    "summer",
    "holidays",
    "vacation",
    "relax"
  ],
  leaf: [
    "nature",
    "leaf",
    "eco",
    "ecology",
    "sustainability",
    "forest",
    "green"
  ],
  leafOak: [
    "nature",
    "leaf",
    "eco",
    "ecology",
    "sustainability",
    "forest",
    "green"
  ],
  letter: ["letter", "send", "message", "communication"],
  letterHeart: ["letter", "send", "message", "communication", "love", "heart"],
  location: [
    "location",
    "map",
    "googlemaps",
    "google maps",
    "travel",
    "vacation"
  ],
  mapLocation: ["map", "location", "travel", "holidays", "vacation"],
  message: ["message", "text", "conversation", "communication", "social"],
  messageTxt: ["message", "text", "conversation", "communication", "social"],
  moon: ["moon", "sky", "space", "nature", "night", "weather"],
  mushroom: ["nature", "mushroom", "forest", "nature"],
  mushroomDots: ["nature", "mushroom", "forest", "nature"],
  musicNote: ["music", "note", "radio", "sound", "art"],
  palette: ["palette", "colors", "color", "paint", "art", "design", "graphic"],
  phone: ["phone", "telephone", "responsive", "technology"],
  phoneHeart: [
    "phone",
    "telephone",
    "responsive",
    "love",
    "heart",
    "technology"
  ],
  plant: ["plant", "nature", "sustainability", "eco", "ecology"],
  plantTall: ["plant", "nature", "sustainability", "eco", "ecology"],
  popcorn: ["food", "snack", "cinema", "movie", "movies"],
  search: ["search", "technology", "zoom"],
  shoppingBag: ["search", "technology", "zoom"],
  shoppingBagDiscount: ["search", "technology", "zoom"],
  sun: [
    "sun",
    "weather",
    "nature",
    "space",
    "sky",
    "happy",
    "sea",
    "seaside",
    "summer",
    "beach",
    "vacation",
    "holidays",
    "travel"
  ],
  tablet: ["tablet", "texhnology", "it", "computer", "technology"],
  tabletHeart: [
    "tablet",
    "texhnology",
    "it",
    "computer",
    "heart",
    "love",
    "technology"
  ]
};
